name: dart2_fix
description: A tool to migrate API usage to Dart 2.
version: 1.0.0-dev

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  analyzer: 0.31.2-alpha.1
  args: ^1.4.0

dev_dependencies:
  test: ^0.12.0
